
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
/**
 * Replace the settings snapshot: persist to disk, sync side effects
 * (autostart registration), swap the in-memory copy. Returns the new
 * snapshot so the frontend stays consistent without a second call.
 */
async updateSettings(settings: AppSettings) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List compiled-in modules with their enabled state — drives the onboarding
 * picker and the settings module list.
 */
async listModules() : Promise<ModuleInfo[]> {
    return await TAURI_INVOKE("list_modules");
},
async authStatus() : Promise<AuthStatus> {
    return await TAURI_INVOKE("auth_status");
},
/**
 * Kick off the browser login. Fails fast when no server is configured.
 */
async loginStart() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The signed-in user's Discord profile, from `GET /api/me`.
 */
async fetchProfile() : Promise<Result<Profile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop the device token. Purely local — server-side revocation is a
 * `svc-sync` concern once token management lands there.
 */
async logout() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = 
/**
 * Something the user can fix in Settings (missing server URL, …).
 */
{ kind: "Config"; message: string } | 
/**
 * Auth / token problems (keyring access, bad callback, …).
 */
{ kind: "Auth"; message: string } | 
/**
 * Everything else — bugs and IO surprises.
 */
{ kind: "Internal"; message: string }
/**
 * App-global preferences surfaced to the Settings page.
 * 
 * `#[serde(default)]` keeps old settings files loading after new fields are
 * added — never rename or repurpose a field, add a new one.
 */
export type AppSettings = { 
/**
 * Whether the first-launch onboarding has been completed/skipped.
 */
onboarding_completed: boolean; 
/**
 * Launch hidden to tray (companion mode). Also forced by `--minimized`,
 * which autostart passes.
 */
start_minimized: boolean; 
/**
 * Closing the main window hides to tray instead of quitting.
 */
close_to_tray: boolean; 
/**
 * Run at login (delegated to the autostart plugin on update).
 */
autostart: boolean; 
/**
 * Starlume server base URL. `None` → all online features disabled.
 * A default ships once the server exists.
 */
server_url: string | null; 
/**
 * Feature modules the user enabled in onboarding/settings. Module ids
 * not in this list stay invisible in the UI.
 */
enabled_modules: string[] }
export type AuthStatus = { 
/**
 * A device token is present in the credential store.
 */
logged_in: boolean; 
/**
 * A server URL is configured — login is possible at all.
 */
server_configured: boolean }
export type ModuleInfo = { id: string; name: string; description: string; enabled: boolean }
export type Profile = { username: string; avatar_url: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
