
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
/**
 * Replace the settings snapshot: persist to disk, sync side effects
 * (autostart registration), swap the in-memory copy. Returns the new
 * snapshot so the frontend stays consistent without a second call.
 */
async updateSettings(settings: AppSettings) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the gRPC sub-features this build knows — drives the Settings toggles.
 */
async listGrpcFeatures() : Promise<GrpcFeatureInfo[]> {
    return await TAURI_INVOKE("list_grpc_features");
},
/**
 * List compiled-in modules with their enabled state — drives the onboarding
 * picker and the settings module list.
 */
async listModules() : Promise<ModuleInfo[]> {
    return await TAURI_INVOKE("list_modules");
},
async authStatus() : Promise<AuthStatus> {
    return await TAURI_INVOKE("auth_status");
},
/**
 * Kick off the browser login. Fails fast when no server is configured.
 */
async loginStart() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The signed-in user's Discord profile, from `GET /api/me`.
 */
async fetchProfile() : Promise<Result<Profile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop the device token. Purely local — server-side revocation is a
 * `svc-sync` concern once token management lands there.
 */
async logout() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = 
/**
 * Something the user can fix in Settings (missing server URL, …).
 */
{ kind: "Config"; message: string } | 
/**
 * Auth / token problems (keyring access, bad callback, …).
 */
{ kind: "Auth"; message: string } | 
/**
 * Everything else — bugs and IO surprises.
 */
{ kind: "Internal"; message: string }
/**
 * App-global preferences surfaced to the Settings page.
 * 
 * `#[serde(default)]` keeps old settings files loading after new fields are
 * added — never rename or repurpose a field, add a new one.
 */
export type AppSettings = { 
/**
 * Whether the first-launch onboarding has been completed/skipped.
 */
onboarding_completed: boolean; 
/**
 * Launch hidden to tray (companion mode). Also forced by `--minimized`,
 * which autostart passes.
 */
start_minimized: boolean; 
/**
 * Closing the main window hides to tray instead of quitting.
 */
close_to_tray: boolean; 
/**
 * Minimizing the main window hides it to tray instead of the taskbar.
 * Default off — taskbar minimize is the common expectation; tray purists
 * opt in.
 */
minimize_to_tray: boolean; 
/**
 * Run at login (delegated to the autostart plugin on update).
 */
autostart: boolean; 
/**
 * Starlume server base URL. `None` → all online features disabled.
 * A default ships once the server exists.
 */
server_url: string | null; 
/**
 * Feature modules the user enabled in onboarding/settings. Module ids
 * not in this list stay invisible in the UI.
 */
enabled_modules: string[]; 
/**
 * Master online switch (default ON). Off → no Discord auth, no RSI
 * fetch, no gRPC — no network calls except **update checks** (the one
 * documented exception; see CLAUDE.md). Enforced via
 * [`AppState::require_online`](crate::AppState).
 */
online_enabled: boolean; 
/**
 * Master switch for CIG game-services (gRPC) calls — the ToS-grey
 * surface (default OFF, opt-in). Preserved but inert while
 * `online_enabled` is off. Enforced via `AppState::require_grpc`.
 */
grpc_enabled: boolean; 
/**
 * One-time ToS acknowledgement — set automatically the first time
 * `grpc_enabled` flips on (the UI shows the consent dialog before that).
 */
grpc_consented: boolean; 
/**
 * Per-sub-feature allow-list for gRPC calls (ids from
 * [`GRPC_FEATURES`]), so users can enable e.g. blueprints but not
 * missions. A feature is live only when `online_enabled` +
 * `grpc_enabled` + membership here all hold.
 */
grpc_features: string[]; 
/**
 * Show native OS toasts for notifications raised while the window is
 * hidden/minimized (companion mode). Default ON — a hidden tray app has
 * no other way to reach the user.
 */
native_notifications: boolean }
export type AuthStatus = { 
/**
 * A device token is present in the credential store.
 */
logged_in: boolean; 
/**
 * A server URL is configured — login is possible at all.
 */
server_configured: boolean }
/**
 * A gRPC sub-feature users can individually allow. The registry grows as
 * dossier-backed features land (blueprints, missions, inventory,
 * reputation, entitlements/ships…) — each new gRPC call site names its
 * feature id here and gates through `AppState::require_grpc(id)`.
 */
export type GrpcFeatureInfo = { id: string; name: string; description: string }
export type ModuleInfo = { id: string; name: string; description: string; enabled: boolean }
export type Profile = { username: string; avatar_url: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
